#!/bin/bash

# Signal desktop hot n' ready to trigger services {sxhkd,compton,dunst,etc}
systemctl --no-block --user import-environment
systemctl --no-block --user start bspwm-session.target

# 'virtual' desktop setup
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Visual options
bspc config border_width        0
bspc config window_gap          0

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config focus_follows_pointer true

# Rules
#bspc rule -a zathura state=tiled
#bspc rule -a keepassxc state=tiled
bspc rule -a emacs state=tiled
bspc rule -a feh floating=on manage=off
