#!/bin/sh

bspc config border_width        1
bspc config window_gap          0

bspc monitor DVI-I-1 -n "1" -d 1 2 3 4 5 6 7 8 9

# Visual options
bspc config split_ratio         0.666666
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#808080"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
#bspc config normal_frame_opacity 0.0
#bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off

